name: earlips
description: Sleep and Liver Care Management Application
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.1.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    collection: any
    cupertino_icons: ^1.0.2
    flutter_native_splash: ^2.3.6
    flutter_dotenv: ^5.1.0
    flutter_launcher_icons: ^0.13.1
    get: ^4.6.6
    flutter_svg: ^2.0.9
    intl: ^0.18.1
    firebase_core: ^2.25.4
    firebase_auth: ^4.17.4
    google_sign_in: ^6.2.1
    fl_chart: ^0.66.2
    percent_indicator: ^4.2.3
    speech_to_text: ^6.6.0
    permission_handler: ^8.0.0
    flutter_secure_storage: ^9.0.0
    flutter_sound: ^9.2.13
    flutter_annual_task: ^0.2.0
    flutter_calendar_week: ^3.0.2
    firebase_database: ^10.4.5
    cloud_firestore: ^4.15.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.1
    intl_translation: ^0.18.1

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/icons/
        - assets/config/.env
        - assets/data/
        - assets/images/home/
        - assets/images/study/
    #        - assets/sounds/speech_to_text_listening.m4r
    #        - assets/sounds/speech_to_text_cancel.m4r
    #        - assets/sounds/speech_to_text_stop.m4r

    fonts:
        - family: Pretendard
          fonts:
              - asset: assets/fonts/Pretendard-Thin.otf
                weight: 100
              - asset: assets/fonts/Pretendard-ExtraLight.otf
                weight: 200
              - asset: assets/fonts/Pretendard-Light.otf
                weight: 300
              - asset: assets/fonts/Pretendard-Regular.otf
                weight: 400
              - asset: assets/fonts/Pretendard-Medium.otf
                weight: 500
              - asset: assets/fonts/Pretendard-SemiBold.otf
                weight: 600
              - asset: assets/fonts/Pretendard-Bold.otf
                weight: 700
              - asset: assets/fonts/Pretendard-ExtraBold.otf
                weight: 800
              - asset: assets/fonts/Pretendard-Black.otf
                weight: 900
